version: "3.5"

networks:
  app-network:
    name: app-network
    driver: bridge

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    env_file:
      - .env
    volumes:
      - "~/Bureau/inception/mariadb:/var/lib/mysql"
    networks:
      - app-network
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - "~/Bureau/inception/website:/var/www/html"
    networks:
      - app-network
    restart: unless-stopped

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - "~/Bureau/inception/website:/var/www/html"
    networks:
      - app-network
    restart: unless-stopped
