version: "3.5"

networks:
  inceptionNetwork:
    name: inceptionNetwork
    driver: bridge

services:
  mariadb:
    container_name: mariadb
    image: mariadb
    build: ./requirements/mariadb
    env_file:
      - .env
    volumes:
      - "DB:/var/lib/mysql"
    networks:
      - inceptionNetwork
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    image: wordpress
    build: ./requirements/wordpress
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - "WordPress:/var/www/html"
    networks:
      - inceptionNetwork
    restart: unless-stopped

  nginx:
    container_name: nginx
    image: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - "WordPress:/var/www/html"
    networks:
      - inceptionNetwork
    restart: unless-stopped


volumes:
  DB:
    name: DB
    driver: local
    driver_opts:
      type: volume
      device: "/home/vchevill/data/mariadb"
      o: bind

  WordPress:
    name: WordPress
    driver: local
    driver_opts:
      type: volume
      device: "/home/vchevill/data/website"
      o: bind
